[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/save"
  to = "/.netlify/functions/save"
  status = 200

[[headers]]
  for = "/content.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
